// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestStationService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestStationService.Models.Client", b =>
                {
                    b.Property<int>("IdCli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCli"));

                    b.Property<string>("NomCli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrenomCli")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelCli")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdCli");

                    b.ToTable("table_client", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Cuve", b =>
                {
                    b.Property<int>("IdCuve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuve"));

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("int");

                    b.Property<int>("IdProd")
                        .HasColumnType("int");

                    b.Property<int>("NiveauActu")
                        .HasColumnType("int");

                    b.HasKey("IdCuve");

                    b.HasIndex("IdProd");

                    b.ToTable("table_cuve", null, t =>
                        {
                            t.HasCheckConstraint("NiveauActu_inf_CapaciteMax", "[NiveauActu] <= [CapaciteMax]");
                        });
                });

            modelBuilder.Entity("GestStationService.Models.Employe", b =>
                {
                    b.Property<int>("IdEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmp"));

                    b.Property<string>("MDPHash")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("NomEmp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrenomEmp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleEmp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdEmp");

                    b.ToTable("table_employe", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaye"));

                    b.Property<DateTime>("DatePaye")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVente")
                        .HasColumnType("int");

                    b.Property<string>("ModePaye")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPaye");

                    b.HasIndex("IdVente");

                    b.ToTable("table_paiement", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Pompe", b =>
                {
                    b.Property<int>("IdPompe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPompe"));

                    b.Property<string>("EtatP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProd")
                        .HasColumnType("int");

                    b.Property<string>("LibelleP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("VolTotalDist")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPompe");

                    b.HasIndex("IdProd");

                    b.ToTable("table_pompe", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Produit", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProd"));

                    b.Property<string>("NomProd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TypeCarb")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdProd");

                    b.ToTable("table_produit", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Vente", b =>
                {
                    b.Property<int>("IdVente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVente"));

                    b.Property<DateTime>("DateEmis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCli")
                        .HasColumnType("int");

                    b.Property<int>("IdEmp")
                        .HasColumnType("int");

                    b.Property<int>("IdPompe")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantV")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumFact")
                        .HasColumnType("int");

                    b.Property<int>("QteLitre")
                        .HasColumnType("int");

                    b.Property<string>("StatutFact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdVente");

                    b.HasIndex("IdCli");

                    b.HasIndex("IdEmp");

                    b.HasIndex("IdPompe");

                    b.ToTable("table_vente", (string)null);
                });

            modelBuilder.Entity("GestStationService.Models.Cuve", b =>
                {
                    b.HasOne("GestStationService.Models.Produit", "Produit")
                        .WithMany("Cuve")
                        .HasForeignKey("IdProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestStationService.Models.Paiement", b =>
                {
                    b.HasOne("GestStationService.Models.Vente", "Vente")
                        .WithMany("Paiement")
                        .HasForeignKey("IdVente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestStationService.Models.Pompe", b =>
                {
                    b.HasOne("GestStationService.Models.Produit", "Produit")
                        .WithMany("Pompe")
                        .HasForeignKey("IdProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestStationService.Models.Vente", b =>
                {
                    b.HasOne("GestStationService.Models.Client", "Client")
                        .WithMany("Vente")
                        .HasForeignKey("IdCli")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestStationService.Models.Employe", "Employe")
                        .WithMany("Vente")
                        .HasForeignKey("IdEmp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestStationService.Models.Pompe", "Pompe")
                        .WithMany("Vente")
                        .HasForeignKey("IdPompe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employe");

                    b.Navigation("Pompe");
                });

            modelBuilder.Entity("GestStationService.Models.Client", b =>
                {
                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestStationService.Models.Employe", b =>
                {
                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestStationService.Models.Pompe", b =>
                {
                    b.Navigation("Vente");
                });

            modelBuilder.Entity("GestStationService.Models.Produit", b =>
                {
                    b.Navigation("Cuve");

                    b.Navigation("Pompe");
                });

            modelBuilder.Entity("GestStationService.Models.Vente", b =>
                {
                    b.Navigation("Paiement");
                });
#pragma warning restore 612, 618
        }
    }
}
